### PR TITLE
Ploneorg5 adjustments

### PR DESCRIPTION
**Pull request by loechel**
@svx / @polyester make the ploneorg5 theme really plone.org 5 look like, this adjusts the color schema to do so.
might merge for release of plone 5.1

### CODE REVIEW

**Comment by loechel** [comment]
Image how the new color schema would look like:

fireshot capture 42 - plone - the open source cms plone do_ - file____usr_local_plone_sphinx bui

**Comment by svx** [comment]
@loechel cool ! Thanks a lot ! 

I will leave this PR, open, and will merge it when we go online with the 5.1 docs !

Thanks a lot !

**Comment by svx** [comment]
**PLEASE DO NOT MERGE YET**

If the time is come, I will merge !

**Comment by loechel** [comment]
@svx now it should be resolved and mergeable again. 
You may look this thread to prevent merging before release of Plone 5.1

**Comment by svx** [comment]
@loechel yeah, good point !

For now I looked the master and this branch, after 5.1 is released I will remove the restricted permissions !

Thanks for the rebase !!!

**Comment by loechel** [comment]
this pull request is superseed by #60 as rebasing this is to much work.

**Pull request closed without merging**
